wandb_version: 1

LR:
  desc: null
  value: 0.00025
NUM_ENVS:
  desc: null
  value: 1000
NUM_STEPS:
  desc: null
  value: 10
TOTAL_TIMESTEPS:
  desc: null
  value: 10000000.0
UPDATE_EPOCHS:
  desc: null
  value: 4
NUM_MINIBATCHES:
  desc: null
  value: 4
GAMMA:
  desc: null
  value: 0.99
GAE_LAMBDA:
  desc: null
  value: 0.95
CLIP_EPS:
  desc: null
  value: 0.2
ENT_COEF:
  desc: null
  value: 0.01
VF_COEF:
  desc: null
  value: 0.5
MAX_GRAD_NORM:
  desc: null
  value: 0.5
ENV_NAME:
  desc: null
  value: alphatradeExec-v0
ANNEAL_LR:
  desc: null
  value: true
DEBUG:
  desc: null
  value: true
NORMALIZE_ENV:
  desc: null
  value: true
ATFOLDER:
  desc: null
  value: ../AlphaTrade
TASKSIDE:
  desc: null
  value: buy
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.5
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689354708.469927
    t:
      1:
      - 2
      - 3
      - 12
      - 45
      - 55
      2:
      - 2
      - 3
      - 12
      - 45
      - 55
      3:
      - 16
      - 23
      4: 3.10.11
      5: 0.15.5
      8:
      - 5
