"LR": 0.0004
"NUM_ENVS": 128
"NUM_STEPS": 256
"GRU_HIDDEN_DIM": 128
"FC_DIM_SIZE": 128
"TOTAL_TIMESTEPS": 1e8
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 16
"GAMMA": 0.999
"GAE_LAMBDA": 0.99
"CLIP_EPS": 0.2
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.01
"VF_COEF": 0.00000000000001
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "relu"
"ENV_NAME": "HeuristicEnemySMAX"
#"NUM_AGENTS_PER_TYPE": [2,2]
"SEED": 0
# "ENV_KWARGS": 
#   "see_enemy_actions": True
#   "walls_cause_death": True
#   "attack_mode": "closest"
"ANNEAL_LR": True

# WandB Params
"ENTITY": "oxford-lob"
"PROJECT": "JAXMARLLOB_MM_simple"
"WANDB_MODE" : "online"