wandb_version: 1

policy_type:
  desc: null
  value: MlpLstmPolicy
total_timesteps:
  desc: null
  value: 50000
ent_coef:
  desc: null
  value: 0.5
vf_coef:
  desc: null
  value: 0.5
gamma:
  desc: null
  value: 1
gae_lambda:
  desc: null
  value: 0.95
clip_range:
  desc: null
  value: 0.5
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688823851.51146
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 55
      3:
      - 16
      - 23
      - 35
      4: 3.10.11
      5: 0.15.4
      8:
      - 5
